name: CI/CD with Github Actions

on: 
 push: 
   branches: 
     - main


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  

    - name: Deploy to EC2 and run docker container
      env:
        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        echo "$PRIVATE_KEY" > private_key.pem
        chmod 400 private_key.pem

        # Copy entire codebase to EC2
        rsync -avz -e "ssh -i private_key.pem -o StrictHostKeyChecking=no" --exclude '.git/' . $USER@$HOST:~/test_project 

        # SSH into EC2 and build & run Docker container
        ssh -i private_key.pem -o StrictHostKeyChecking=no $USER@$HOST <<EOF
          cd ~/test_project
          docker stop myapp-container
          docker rm myapp-container
          docker rmi myapp:latest
          docker build -t myapp:latest .
          docker run --name myapp-container -d -p 5515:80 myapp:latest
        EOF

        rm -f private_key.pem   

         
          

